// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres.gdpoqpbqjbrrrdkgznuo:Vx5nz4Z8LURMSrnj@aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require",
  },
});
